description = "Flowerwork builder for the Ubuntu 20.04 focal stack"

[[buildpacks]]
id = "flowerworkio/asdf"
uri = "asdf"
version = "0.0.2"

[[buildpacks]]
id = "flowerworkio/phoenix"
uri = "phoenix"
version = "0.0.2"

[[order]]
  [[order.group]]
  id = "flowerworkio/asdf"
  version = "0.0.2"
  [[order.group]]
  id = "flowerworkio/phoenix"
  version = "0.0.2"

[stack]
id = "io.flowerwork.stacks.focal"
run-image = "flowerworkio/run:focal"
build-image = "flowerworkio/build:focal"

[lifecycle]
version = "0.13.2"
