[[buildpacks]]
id = "flowerworkio/asdf"
uri = "asdf"
version = "0.0.1"

# Order used for detection
[[order]]
  [[order.group]]
  id = "flowerworkio/asdf"
  version = "0.0.1"

[stack]
id = "io.flowerwork.stacks.focal"
# This image is used at runtime
run-image = "flowerworkio/run:focal"
# This image is used at build-time
build-image = "flowerworkio/build:focal"

[lifecycle]
version = "0.13.2"
