#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname "$0")/../.."

brew_add_to_shell() {
  describe "Add homebrew to shell"
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
}

describe() {
  echo "--- $1…"
}

if [ "$BUILDKITE_STEP_KEY" == "ci" ]; then
  brew_add_to_shell
else
  describe "Skipping pre-command hook"
fi
